coverage:
    precision: 2
    round: down
    range: "70...100"

    status:
        project:
            enabled: yes
            target: auto
            if_no_uploads: error
            if_not_found: success
            if_ci_failed: error

        patch:
            enabled: yes
            target: "80%"
            if_no_uploads: error
            if_not_found: success
            if_ci_failed: error

comment:
    layout: "diff, changes"
    behavior: spammy
